import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './styles/index.css'
import MainHeader from './components/mainheader'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=''>
          <MainHeader />
        </div>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
